development:
  url: {{envOr "DATABASE_URL" "postgres://postgres:JAMAC88@127.0.0.1:5432/booking?sslmode=disable"}}
  dialect: postgres
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:JAMAC88@127.0.0.1:5432/booking_test?sslmode=disable"}}
  dialect: postgres
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:JAMAC88@127.0.0.1:5432/booking_production?sslmode=disable"}}
  dialect: postgres
  pool: 5
